/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PublicTransportationSystem.GUIs;

import static PublicTransportationSystem.GUIs.AppSwitchboard.mainUI;
import PublicTransportationSystem.Journey;
import PublicTransportationSystem.SetOfUsers;
import PublicTransportationSystem.TravelSystem;
import PublicTransportationSystem.TypeEnums;
import PublicTransportationSystem.User;
import PublicTransportationSystem.Zone;
import PublicTransportationSystem.ZoneList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jonathondickson
 */
public class AdminUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        dlg_adminJourneyEdit = new javax.swing.JDialog();
        lbl_adminJourneyEditTitle = new javax.swing.JLabel();
        cmb_departure = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_arrival = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_offPeakPrice = new javax.swing.JTextField();
        txt_onPeakPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_savePriceChanges = new javax.swing.JButton();
        btn_closeEditJourney = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();
        dlg_adminUserAddEdit = new javax.swing.JDialog();
        pnl_adminUserAddEditContainer = new javax.swing.JPanel();
        txt_adminUserAddEditForename = new javax.swing.JTextField();
        txt_adminUserAddEditSurname = new javax.swing.JTextField();
        txt_adminUserAddEditUsername = new javax.swing.JTextField();
        txt_adminUserAddEditPassword = new javax.swing.JTextField();
        lbl_adminUserAddEditForename = new javax.swing.JLabel();
        lbl_adminUserAddEditSurname = new javax.swing.JLabel();
        lbl_adminUserAddEditUsername = new javax.swing.JLabel();
        lbl_adminUserAddEditPassword = new javax.swing.JLabel();
        lbl_adminUserAddEditUserRole = new javax.swing.JLabel();
        lbl_adminUserAddEditId = new javax.swing.JLabel();
        txt_adminUserAddEditId = new javax.swing.JTextField();
        lbl_adminUserAddEditEmail = new javax.swing.JLabel();
        txt_adminUserAddEditEmail = new javax.swing.JTextField();
        btn_adminUserAddEditSave = new javax.swing.JButton();
        btn_adminUserAddEditCancel = new javax.swing.JButton();
        cmd_adminUserAddEditUserRole = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        pnl_adminGUITitle = new javax.swing.JPanel();
        lbl_managementUITitle = new javax.swing.JLabel();
        pnl_adminGUITabs = new javax.swing.JPanel();
        tab_admin = new javax.swing.JTabbedPane();
        pnl_adminHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_adminGUIUserList = new javax.swing.JTable();
        btn_adminUserAdd = new javax.swing.JButton();
        btn_adminUserEdit = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_adminUserDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_editJourneys = new javax.swing.JButton();

        dlg_adminJourneyEdit.setResizable(false);
        dlg_adminJourneyEdit.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dlg_adminJourneyEditWindowOpened(evt);
            }
        });

        lbl_adminJourneyEditTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbl_adminJourneyEditTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_adminJourneyEditTitle.setText("Edit Journey");

        cmb_departure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_departure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_departureActionPerformed(evt);
            }
        });
        cmb_departure.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb_departurePropertyChange(evt);
            }
        });

        jLabel5.setText("Departure Zone");

        jLabel6.setText("Arrival Zone");

        cmb_arrival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_arrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_arrivalActionPerformed(evt);
            }
        });
        cmb_arrival.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb_arrivalPropertyChange(evt);
            }
        });

        jLabel7.setText("Off Peak");

        jLabel8.setText("On Peak");

        btn_savePriceChanges.setText("Save");
        btn_savePriceChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_savePriceChangesActionPerformed(evt);
            }
        });

        btn_closeEditJourney.setText("Cancel");
        btn_closeEditJourney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeEditJourneyActionPerformed(evt);
            }
        });

        lbl_error.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error.setText("Off Peak is greater than On Peak");

        javax.swing.GroupLayout dlg_adminJourneyEditLayout = new javax.swing.GroupLayout(dlg_adminJourneyEdit.getContentPane());
        dlg_adminJourneyEdit.getContentPane().setLayout(dlg_adminJourneyEditLayout);
        dlg_adminJourneyEditLayout.setHorizontalGroup(
            dlg_adminJourneyEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg_adminJourneyEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg_adminJourneyEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_adminJourneyEditTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_departure, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_arrival, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_adminJourneyEditLayout.createSequentialGroup()
                        .addGroup(dlg_adminJourneyEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(txt_offPeakPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlg_adminJourneyEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlg_adminJourneyEditLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_closeEditJourney)
                                .addGap(1, 1, 1)
                                .addComponent(btn_savePriceChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlg_adminJourneyEditLayout.createSequentialGroup()
                                .addComponent(lbl_error)
                                .addGap(0, 19, Short.MAX_VALUE))))
                    .addGroup(dlg_adminJourneyEditLayout.createSequentialGroup()
                        .addComponent(txt_onPeakPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dlg_adminJourneyEditLayout.setVerticalGroup(
            dlg_adminJourneyEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg_adminJourneyEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adminJourneyEditTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_departure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_arrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlg_adminJourneyEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_offPeakPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_error))
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_onPeakPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(dlg_adminJourneyEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_closeEditJourney)
                    .addComponent(btn_savePriceChanges))
                .addContainerGap())
        );

        txt_adminUserAddEditForename.setEnabled(false);

        txt_adminUserAddEditSurname.setEnabled(false);

        txt_adminUserAddEditUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adminUserAddEditUsernameActionPerformed(evt);
            }
        });

        lbl_adminUserAddEditForename.setText("Forename");

        lbl_adminUserAddEditSurname.setText("Surname");

        lbl_adminUserAddEditUsername.setText("Username");

        lbl_adminUserAddEditPassword.setText("Password");

        lbl_adminUserAddEditUserRole.setText("User Role");

        lbl_adminUserAddEditId.setText("ID");

        txt_adminUserAddEditId.setText("userid");
        txt_adminUserAddEditId.setEnabled(false);

        lbl_adminUserAddEditEmail.setText("Email");

        btn_adminUserAddEditSave.setText("Save");

        btn_adminUserAddEditCancel.setText("Cancel");

        cmd_adminUserAddEditUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnl_adminUserAddEditContainerLayout = new javax.swing.GroupLayout(pnl_adminUserAddEditContainer);
        pnl_adminUserAddEditContainer.setLayout(pnl_adminUserAddEditContainerLayout);
        pnl_adminUserAddEditContainerLayout.setHorizontalGroup(
            pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_adminUserAddEditContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_adminUserAddEditCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_adminUserAddEditSave)
                .addContainerGap())
            .addGroup(pnl_adminUserAddEditContainerLayout.createSequentialGroup()
                .addComponent(cmd_adminUserAddEditUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnl_adminUserAddEditContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_adminUserAddEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_adminUserAddEditContainerLayout.createSequentialGroup()
                        .addGroup(pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_adminUserAddEditForename, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_adminUserAddEditForename))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_adminUserAddEditSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_adminUserAddEditSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_adminUserAddEditPassword)
                    .addComponent(lbl_adminUserAddEditUserRole)
                    .addComponent(txt_adminUserAddEditId, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_adminUserAddEditId)
                    .addGroup(pnl_adminUserAddEditContainerLayout.createSequentialGroup()
                        .addGroup(pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_adminUserAddEditUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_adminUserAddEditUsername))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_adminUserAddEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_adminUserAddEditEmail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_adminUserAddEditContainerLayout.setVerticalGroup(
            pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adminUserAddEditContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adminUserAddEditId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_adminUserAddEditId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_adminUserAddEditContainerLayout.createSequentialGroup()
                        .addGroup(pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_adminUserAddEditForename)
                            .addComponent(lbl_adminUserAddEditSurname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_adminUserAddEditForename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_adminUserAddEditSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_adminUserAddEditUsername))
                    .addComponent(lbl_adminUserAddEditEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_adminUserAddEditUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_adminUserAddEditEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lbl_adminUserAddEditPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_adminUserAddEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbl_adminUserAddEditUserRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_adminUserAddEditUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pnl_adminUserAddEditContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adminUserAddEditSave)
                    .addComponent(btn_adminUserAddEditCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout dlg_adminUserAddEditLayout = new javax.swing.GroupLayout(dlg_adminUserAddEdit.getContentPane());
        dlg_adminUserAddEdit.getContentPane().setLayout(dlg_adminUserAddEditLayout);
        dlg_adminUserAddEditLayout.setHorizontalGroup(
            dlg_adminUserAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(dlg_adminUserAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dlg_adminUserAddEditLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(pnl_adminUserAddEditContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );
        dlg_adminUserAddEditLayout.setVerticalGroup(
            dlg_adminUserAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
            .addGroup(dlg_adminUserAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dlg_adminUserAddEditLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnl_adminUserAddEditContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Management UI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbl_managementUITitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lbl_managementUITitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_managementUITitle.setText("Management GUI");

        javax.swing.GroupLayout pnl_adminGUITitleLayout = new javax.swing.GroupLayout(pnl_adminGUITitle);
        pnl_adminGUITitle.setLayout(pnl_adminGUITitleLayout);
        pnl_adminGUITitleLayout.setHorizontalGroup(
            pnl_adminGUITitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_managementUITitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_adminGUITitleLayout.setVerticalGroup(
            pnl_adminGUITitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adminGUITitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_managementUITitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Useful statistics ");

        javax.swing.GroupLayout pnl_adminHomeLayout = new javax.swing.GroupLayout(pnl_adminHome);
        pnl_adminHome.setLayout(pnl_adminHomeLayout);
        pnl_adminHomeLayout.setHorizontalGroup(
            pnl_adminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adminHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_adminHomeLayout.setVerticalGroup(
            pnl_adminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adminHomeLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        tab_admin.addTab("Home", pnl_adminHome);

        tbl_adminGUIUserList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Forename", "Surname", "Username", "User Role", "Email", "Date of Birth"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_adminGUIUserList.setColumnSelectionAllowed(true);
        tbl_adminGUIUserList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_adminGUIUserList.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_adminGUIUserList);
        tbl_adminGUIUserList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btn_adminUserAdd.setText("Add");
        btn_adminUserAdd.setPreferredSize(new java.awt.Dimension(97, 29));

        btn_adminUserEdit.setText("Edit");
        btn_adminUserEdit.setPreferredSize(new java.awt.Dimension(97, 29));

        btn_logout.setText("Logout");
        btn_logout.setPreferredSize(new java.awt.Dimension(97, 29));

        btn_adminUserDelete.setText("Delete");
        btn_adminUserDelete.setPreferredSize(new java.awt.Dimension(97, 29));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_adminUserDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_adminUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_adminUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adminUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adminUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adminUserDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_admin.addTab("Users", jPanel1);

        btn_editJourneys.setText("Edit Journeys");
        btn_editJourneys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editJourneysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(576, Short.MAX_VALUE)
                .addComponent(btn_editJourneys)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(417, Short.MAX_VALUE)
                .addComponent(btn_editJourneys)
                .addContainerGap())
        );

        tab_admin.addTab("Journeys", jPanel2);

        javax.swing.GroupLayout pnl_adminGUITabsLayout = new javax.swing.GroupLayout(pnl_adminGUITabs);
        pnl_adminGUITabs.setLayout(pnl_adminGUITabsLayout);
        pnl_adminGUITabsLayout.setHorizontalGroup(
            pnl_adminGUITabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_admin, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnl_adminGUITabsLayout.setVerticalGroup(
            pnl_adminGUITabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adminGUITabsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_admin))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_adminGUITitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnl_adminGUITabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_adminGUITitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_adminGUITabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
//            jlist_adminGUIUserList.setModel(new DefaultListModel());
//            jlist_adminGUIUserList.setListData((Vector) TravelSystem.getInstance().getUsers());
            populateTable();
            TypeEnums.UserType[] userTypes = TravelSystem.getInstance().getSystemRoles();
            cmd_adminUserAddEditUserRole.setModel(new DefaultComboBoxModel(userTypes));
        } catch (Throwable ex) {
            Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    public void populateTable() throws Throwable {
        DefaultTableModel model = (DefaultTableModel) tbl_adminGUIUserList.getModel();
        SetOfUsers setUsers = TravelSystem.getInstance().getUsers();

        for (User user : setUsers) {
            model.addRow(new Object[]{user.getId(), user.getForename(), user.getSurname(), user.getUsername(), user.getSystemRole().getName(), user.getEmail(), user.getDob()});
        }
    }

    private void dlg_adminJourneyEditWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlg_adminJourneyEditWindowOpened
        lbl_error.setVisible(false);
    }//GEN-LAST:event_dlg_adminJourneyEditWindowOpened

    private void cmb_departureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_departureActionPerformed
        if (cmb_departure.getItemCount() > 0 && cmb_arrival.getItemCount() > 0) {
            displayPrices();
        }
    }//GEN-LAST:event_cmb_departureActionPerformed

    private void cmb_arrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_arrivalActionPerformed
        if (cmb_departure.getItemCount() > 0 && cmb_arrival.getItemCount() > 0) {
            displayPrices();
        }
    }//GEN-LAST:event_cmb_arrivalActionPerformed

    private void cmb_departurePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb_departurePropertyChange
        if (cmb_departure.isShowing() && cmb_arrival.isShowing()) {
            displayPrices();
        }
    }//GEN-LAST:event_cmb_departurePropertyChange

    private void cmb_arrivalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb_arrivalPropertyChange
        if (cmb_departure.isShowing() && cmb_arrival.isShowing()) {
            displayPrices();
        }
    }//GEN-LAST:event_cmb_arrivalPropertyChange

    private void btn_closeEditJourneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeEditJourneyActionPerformed
        dlg_adminJourneyEdit.dispose();
    }//GEN-LAST:event_btn_closeEditJourneyActionPerformed

    private void btn_savePriceChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_savePriceChangesActionPerformed
        if (cmb_departure.getItemCount() > 0 && cmb_arrival.getItemCount() > 0) {
            Object departure = cmb_departure.getSelectedItem();
            Zone departureZone = ((Zone) departure);
            Object arrival = cmb_arrival.getSelectedItem();
            Zone arrivalZone = ((Zone) arrival);

            try {
                float offPeakPrice = Float.valueOf(txt_offPeakPrice.getText());
                float onPeakPrice = Float.valueOf(txt_onPeakPrice.getText());
                if (offPeakPrice > onPeakPrice) {
                    lbl_error.setVisible(true);
                } else {
                    lbl_error.setVisible(false);
                    editJourney(offPeakPrice, onPeakPrice, departureZone, arrivalZone);
                }
            } catch (Throwable ex) {
                Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_savePriceChangesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        mainUI.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_editJourneysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editJourneysActionPerformed
        // TODO add your handling code here:
        try {
            ZoneList zones = TravelSystem.getInstance().getZones();
            cmb_departure.setModel(new DefaultComboBoxModel(zones));
            cmb_arrival.setModel(new DefaultComboBoxModel(zones));
            dlg_adminJourneyEdit.pack();
            dlg_adminJourneyEdit.setAlwaysOnTop(true);
            dlg_adminJourneyEdit.show();
        } catch (Throwable ex) {
            Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_editJourneysActionPerformed

    private void txt_adminUserAddEditUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adminUserAddEditUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adminUserAddEditUsernameActionPerformed

    private void displayPrices() {
        Object departure = cmb_departure.getSelectedItem();
        Zone departureZone = ((Zone) departure);
        Object arrival = cmb_arrival.getSelectedItem();
        Zone arrivalZone = ((Zone) arrival);

        try {
            Journey journey = TravelSystem.getInstance().getJourneys().getJourney(departureZone, arrivalZone);
            txt_offPeakPrice.setText(Float.toString(journey.getOffPeakPrice()));
            txt_onPeakPrice.setText(Float.toString(journey.getOnPeakPrice()));
        } catch (Throwable ex) {
            Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void editJourney(float newOffPeakPrice, float newOnPeakPrice, Zone startZone, Zone endZone) throws Throwable {
        TravelSystem.getInstance().getJourneys().getJourney(startZone, endZone).setOnPeakPrice(newOnPeakPrice);
        TravelSystem.getInstance().getJourneys().getJourney(startZone, endZone).setOffPeakPrice(newOffPeakPrice);
        System.out.println(TravelSystem.getInstance().getJourneys().getJourney(startZone, endZone).getOffPeakPrice());
        System.out.println(TravelSystem.getInstance().getJourneys().getJourney(startZone, endZone).getOnPeakPrice());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adminUserAdd;
    private javax.swing.JButton btn_adminUserAddEditCancel;
    private javax.swing.JButton btn_adminUserAddEditSave;
    private javax.swing.JButton btn_adminUserDelete;
    private javax.swing.JButton btn_adminUserEdit;
    private javax.swing.JButton btn_closeEditJourney;
    private javax.swing.JButton btn_editJourneys;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_savePriceChanges;
    private javax.swing.JComboBox<String> cmb_arrival;
    private javax.swing.JComboBox<String> cmb_departure;
    private javax.swing.JComboBox<String> cmd_adminUserAddEditUserRole;
    private javax.swing.JDialog dlg_adminJourneyEdit;
    private javax.swing.JDialog dlg_adminUserAddEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_adminJourneyEditTitle;
    private javax.swing.JLabel lbl_adminUserAddEditEmail;
    private javax.swing.JLabel lbl_adminUserAddEditForename;
    private javax.swing.JLabel lbl_adminUserAddEditId;
    private javax.swing.JLabel lbl_adminUserAddEditPassword;
    private javax.swing.JLabel lbl_adminUserAddEditSurname;
    private javax.swing.JLabel lbl_adminUserAddEditUserRole;
    private javax.swing.JLabel lbl_adminUserAddEditUsername;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_managementUITitle;
    private javax.swing.JPanel pnl_adminGUITabs;
    private javax.swing.JPanel pnl_adminGUITitle;
    private javax.swing.JPanel pnl_adminHome;
    private javax.swing.JPanel pnl_adminUserAddEditContainer;
    private javax.swing.JTabbedPane tab_admin;
    private javax.swing.JTable tbl_adminGUIUserList;
    private javax.swing.JTextField txt_adminUserAddEditEmail;
    private javax.swing.JTextField txt_adminUserAddEditForename;
    private javax.swing.JTextField txt_adminUserAddEditId;
    private javax.swing.JTextField txt_adminUserAddEditPassword;
    private javax.swing.JTextField txt_adminUserAddEditSurname;
    private javax.swing.JTextField txt_adminUserAddEditUsername;
    private javax.swing.JTextField txt_offPeakPrice;
    private javax.swing.JTextField txt_onPeakPrice;
    // End of variables declaration//GEN-END:variables
}
