/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PublicTransportationSystem.GUIs;

import static PublicTransportationSystem.GUIs.AppSwitchboard.mainUI;
import PublicTransportationSystem.Journey;
import PublicTransportationSystem.SetOfTickets;
import PublicTransportationSystem.SetOfZones;
import PublicTransportationSystem.SystemRole;
import PublicTransportationSystem.Ticket;
import PublicTransportationSystem.Transaction;
import PublicTransportationSystem.TravelCard;
import PublicTransportationSystem.TravelSystem;
import PublicTransportationSystem.TypeEnums;
import PublicTransportationSystem.User;
import PublicTransportationSystem.Zone;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jonathondickson
 */
public class WebsiteUI extends javax.swing.JFrame {

    User user = null;

    /**
     * Creates new form WebsiteUI
     */
    public WebsiteUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPopup = new javax.swing.JDialog();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        pass_password = new javax.swing.JPasswordField();
        lbl_loginTitle = new javax.swing.JLabel();
        btn_loginPopup = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        lbl_loginErrorMsg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        registerPopup = new javax.swing.JDialog();
        pnl_registerContainer = new javax.swing.JPanel();
        lbl_registerFirstName = new javax.swing.JLabel();
        txt_registerFirstName = new javax.swing.JTextField();
        lbl_registerUsername = new javax.swing.JLabel();
        txt_registerUsername = new javax.swing.JTextField();
        lbl_registerPassword = new javax.swing.JLabel();
        pass_registerPassword = new javax.swing.JPasswordField();
        btn_RegisterSubmit = new javax.swing.JButton();
        txt_registerLastName = new javax.swing.JTextField();
        lbl_registerLastName = new javax.swing.JLabel();
        txt_registerEmail = new javax.swing.JTextField();
        lbl_registerEmail = new javax.swing.JLabel();
        lbl_registerTitle = new javax.swing.JLabel();
        btn_RegisterCancel = new javax.swing.JButton();
        lbl_registerUsernameError = new javax.swing.JLabel();
        lbl_registerEmailError = new javax.swing.JLabel();
        lbl_registerFirstNameError = new javax.swing.JLabel();
        lbl_registerLastNameError = new javax.swing.JLabel();
        lbl_registerPasswordError = new javax.swing.JLabel();
        lbl_registerDobError = new javax.swing.JLabel();
        lbl_registerDob = new javax.swing.JLabel();
        txt_registerDob = new javax.swing.JTextField();
        pnl_websiteContainer = new javax.swing.JPanel();
        txt_websiteURL = new javax.swing.JTextField();
        btn_websiteURLGo = new javax.swing.JButton();
        pnl_websiteMainContainer = new javax.swing.JPanel();
        btn_websiteMainLogout = new javax.swing.JButton();
        txt_websiteMainTitle = new javax.swing.JLabel();
        btn_websiteMainAccount = new javax.swing.JButton();
        pnl_websiteHistoryContainer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_websiteUserJourneysTaken = new javax.swing.JTable();
        pnl_websiteTicketsContainer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmb_websiteToZoneList = new javax.swing.JComboBox();
        cmb_websiteFromZoneList = new javax.swing.JComboBox();
        btn_websitePurchaseTicket = new javax.swing.JButton();
        lbl_websiteToTag = new javax.swing.JLabel();
        lbl_websiteFromTag = new javax.swing.JLabel();
        cmb_websiteTicketType = new javax.swing.JComboBox();
        lbl_websiteToTag1 = new javax.swing.JLabel();
        lbl_websitePurchaseMessage = new javax.swing.JLabel();
        pnl_websiteTravelCardContainer = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_websiteTCBalance = new javax.swing.JLabel();
        lbl_websiteTCStartDate = new javax.swing.JLabel();
        lbl_websiteTCExpiryDate = new javax.swing.JLabel();
        lbl_websiteTCDiscount = new javax.swing.JLabel();
        lbl_websiteTCDailyCap = new javax.swing.JLabel();
        lbl_websiteTCStartDateInput = new javax.swing.JLabel();
        lbl_websiteTCBalanceInput = new javax.swing.JLabel();
        lbl_websiteTCExpiryDateInput = new javax.swing.JLabel();
        lbl_websiteTCDiscountInput = new javax.swing.JLabel();
        lbl_websiteTCDailyCapInput = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        loginPopup.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        loginPopup.setTitle("Login");
        loginPopup.setAlwaysOnTop(true);
        loginPopup.setModal(true);
        loginPopup.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        loginPopup.setResizable(false);
        loginPopup.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                loginPopupWindowClosing(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(204, 255, 255));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(635, 434));

        jLayeredPane2.setBackground(new java.awt.Color(184, 184, 184));
        jLayeredPane2.setOpaque(true);

        lbl_username.setText("Username");

        txt_username.setText("JD");
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_usernameKeyReleased(evt);
            }
        });

        lbl_password.setText("Password");

        pass_password.setText("p");
        pass_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pass_passwordKeyReleased(evt);
            }
        });

        lbl_loginTitle.setBackground(new java.awt.Color(192, 221, 253));
        lbl_loginTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbl_loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_loginTitle.setText("Login");
        lbl_loginTitle.setOpaque(true);

        btn_loginPopup.setText("Login");
        btn_loginPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginPopupActionPerformed(evt);
            }
        });

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        lbl_loginErrorMsg.setForeground(new java.awt.Color(255, 51, 0));
        lbl_loginErrorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_loginErrorMsg.setText("Something went wrong");

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_loginTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_username)
                    .addComponent(pass_password)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_register, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_loginPopup, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_loginErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_loginTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_loginErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_loginPopup)
                    .addComponent(btn_register)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );
        jLayeredPane2.setLayer(lbl_username, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_username, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lbl_password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(pass_password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lbl_loginTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btn_loginPopup, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btn_register, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btn_cancel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lbl_loginErrorMsg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LDN_Underground.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );
        jLayeredPane3.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout loginPopupLayout = new javax.swing.GroupLayout(loginPopup.getContentPane());
        loginPopup.getContentPane().setLayout(loginPopupLayout);
        loginPopupLayout.setHorizontalGroup(
            loginPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPopupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPopupLayout.setVerticalGroup(
            loginPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPopupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        registerPopup.setAlwaysOnTop(true);
        registerPopup.setModal(true);
        registerPopup.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        registerPopup.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                registerPopupWindowClosing(evt);
            }
        });

        lbl_registerFirstName.setText("First Name");

        txt_registerFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_registerFirstNameActionPerformed(evt);
            }
        });

        lbl_registerUsername.setText("Username");

        lbl_registerPassword.setText("Password");

        btn_RegisterSubmit.setText("Register");
        btn_RegisterSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterSubmitActionPerformed(evt);
            }
        });

        lbl_registerLastName.setText("Surname");

        lbl_registerEmail.setText("Email");

        lbl_registerTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbl_registerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_registerTitle.setText("Register");

        btn_RegisterCancel.setText("Cancel");
        btn_RegisterCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterCancelActionPerformed(evt);
            }
        });

        lbl_registerUsernameError.setForeground(new java.awt.Color(255, 0, 0));
        lbl_registerUsernameError.setText("Username already exists!");

        lbl_registerEmailError.setForeground(new java.awt.Color(255, 0, 0));
        lbl_registerEmailError.setText("Email already exists!");

        lbl_registerFirstNameError.setForeground(new java.awt.Color(255, 0, 0));
        lbl_registerFirstNameError.setText("Required");

        lbl_registerLastNameError.setForeground(new java.awt.Color(255, 0, 0));
        lbl_registerLastNameError.setText("Required");

        lbl_registerPasswordError.setForeground(new java.awt.Color(255, 0, 0));
        lbl_registerPasswordError.setText("Required");

        lbl_registerDobError.setForeground(new java.awt.Color(255, 0, 0));
        lbl_registerDobError.setText("Required");

        lbl_registerDob.setText("DOB");

        javax.swing.GroupLayout pnl_registerContainerLayout = new javax.swing.GroupLayout(pnl_registerContainer);
        pnl_registerContainer.setLayout(pnl_registerContainerLayout);
        pnl_registerContainerLayout.setHorizontalGroup(
            pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_registerTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_registerContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registerContainerLayout.createSequentialGroup()
                        .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_RegisterCancel)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_registerContainerLayout.createSequentialGroup()
                                .addComponent(txt_registerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_registerFirstNameError)
                                .addGap(0, 155, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_RegisterSubmit))
                    .addGroup(pnl_registerContainerLayout.createSequentialGroup()
                        .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_registerUsername)
                            .addGroup(pnl_registerContainerLayout.createSequentialGroup()
                                .addComponent(txt_registerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_registerEmailError))
                            .addComponent(lbl_registerLastName)
                            .addGroup(pnl_registerContainerLayout.createSequentialGroup()
                                .addComponent(txt_registerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_registerLastNameError))
                            .addComponent(lbl_registerFirstName)
                            .addGroup(pnl_registerContainerLayout.createSequentialGroup()
                                .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_registerEmail)
                                    .addComponent(pass_registerPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(lbl_registerPassword)
                                    .addComponent(txt_registerUsername)
                                    .addComponent(lbl_registerDob)
                                    .addComponent(txt_registerDob))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_registerUsernameError)
                                    .addComponent(lbl_registerPasswordError)
                                    .addComponent(lbl_registerDobError))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_registerContainerLayout.setVerticalGroup(
            pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registerContainerLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbl_registerTitle)
                .addGap(4, 4, 4)
                .addComponent(lbl_registerFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_registerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_registerFirstNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_registerLastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_registerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_registerLastNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_registerUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_registerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_registerUsernameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_registerEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_registerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_registerEmailError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_registerPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_registerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_registerPasswordError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_registerDob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_registerDobError)
                    .addComponent(txt_registerDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_RegisterSubmit)
                    .addComponent(btn_RegisterCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout registerPopupLayout = new javax.swing.GroupLayout(registerPopup.getContentPane());
        registerPopup.getContentPane().setLayout(registerPopupLayout);
        registerPopupLayout.setHorizontalGroup(
            registerPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_registerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registerPopupLayout.setVerticalGroup(
            registerPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_registerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Website UI");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        txt_websiteURL.setText("  http://www.publictransportsystem.com?l=true&userid=2&frame=websiteui");
        txt_websiteURL.setEnabled(false);
        txt_websiteURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_websiteURLActionPerformed(evt);
            }
        });

        btn_websiteURLGo.setText("Go");
        btn_websiteURLGo.setEnabled(false);

        btn_websiteMainLogout.setText("Log Out");
        btn_websiteMainLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_websiteMainLogoutActionPerformed(evt);
            }
        });

        txt_websiteMainTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        txt_websiteMainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_websiteMainTitle.setText("The Public Transport System");

        btn_websiteMainAccount.setText("My Account");
        btn_websiteMainAccount.setEnabled(false);

        pnl_websiteHistoryContainer.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Your Transactions");

        jLabel5.setText("List here of the users journeys");

        tbl_websiteUserJourneysTaken.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "From", "To", "Cost", "Type", "Used"
            }
        ));
        tbl_websiteUserJourneysTaken.setEnabled(false);
        jScrollPane1.setViewportView(tbl_websiteUserJourneysTaken);

        javax.swing.GroupLayout pnl_websiteHistoryContainerLayout = new javax.swing.GroupLayout(pnl_websiteHistoryContainer);
        pnl_websiteHistoryContainer.setLayout(pnl_websiteHistoryContainerLayout);
        pnl_websiteHistoryContainerLayout.setHorizontalGroup(
            pnl_websiteHistoryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_websiteHistoryContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_websiteHistoryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_websiteHistoryContainerLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 176, Short.MAX_VALUE))
                    .addGroup(pnl_websiteHistoryContainerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_websiteHistoryContainerLayout.setVerticalGroup(
            pnl_websiteHistoryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_websiteHistoryContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Buy Tickets");

        jLabel9.setText("Couple of inputs for user to buy a ticket");

        cmb_websiteToZoneList.setModel(new javax.swing.DefaultComboBoxModel());
        cmb_websiteToZoneList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_websiteToZoneListActionPerformed(evt);
            }
        });

        cmb_websiteFromZoneList.setModel(new javax.swing.DefaultComboBoxModel());
        cmb_websiteFromZoneList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_websiteFromZoneListActionPerformed(evt);
            }
        });

        btn_websitePurchaseTicket.setText("Purchase");
        btn_websitePurchaseTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_websitePurchaseTicketActionPerformed(evt);
            }
        });

        lbl_websiteToTag.setText("To");

        lbl_websiteFromTag.setText("From");

        lbl_websiteToTag1.setText("Type");

        javax.swing.GroupLayout pnl_websiteTicketsContainerLayout = new javax.swing.GroupLayout(pnl_websiteTicketsContainer);
        pnl_websiteTicketsContainer.setLayout(pnl_websiteTicketsContainerLayout);
        pnl_websiteTicketsContainerLayout.setHorizontalGroup(
            pnl_websiteTicketsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_websiteTicketsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_websiteTicketsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(btn_websitePurchaseTicket)
                    .addGroup(pnl_websiteTicketsContainerLayout.createSequentialGroup()
                        .addGroup(pnl_websiteTicketsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_websiteFromZoneList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_websiteFromTag))
                        .addGap(115, 115, 115)
                        .addGroup(pnl_websiteTicketsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_websiteToZoneList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_websiteToTag))
                        .addGap(110, 110, 110)
                        .addGroup(pnl_websiteTicketsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_websiteTicketType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_websiteToTag1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbl_websitePurchaseMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_websiteTicketsContainerLayout.setVerticalGroup(
            pnl_websiteTicketsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_websiteTicketsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_websiteTicketsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_websiteToTag)
                    .addComponent(lbl_websiteFromTag)
                    .addComponent(lbl_websiteToTag1))
                .addGap(7, 7, 7)
                .addGroup(pnl_websiteTicketsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_websiteFromZoneList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_websiteToZoneList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_websiteTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btn_websitePurchaseTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_websitePurchaseMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Your Travel Card");

        lbl_websiteTCBalance.setText("Balance: ");

        lbl_websiteTCStartDate.setText("Start Date:");

        lbl_websiteTCExpiryDate.setText("Expiry Date:");

        lbl_websiteTCDiscount.setText("Active Discount: ");

        lbl_websiteTCDailyCap.setText("Daily Cap:");

        lbl_websiteTCStartDateInput.setText("Input");

        lbl_websiteTCBalanceInput.setText("Input");

        lbl_websiteTCExpiryDateInput.setText("Input");

        lbl_websiteTCDiscountInput.setText("Input");

        lbl_websiteTCDailyCapInput.setText("Input");

        javax.swing.GroupLayout pnl_websiteTravelCardContainerLayout = new javax.swing.GroupLayout(pnl_websiteTravelCardContainer);
        pnl_websiteTravelCardContainer.setLayout(pnl_websiteTravelCardContainerLayout);
        pnl_websiteTravelCardContainerLayout.setHorizontalGroup(
            pnl_websiteTravelCardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_websiteTravelCardContainerLayout.createSequentialGroup()
                .addGroup(pnl_websiteTravelCardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_websiteTravelCardContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(pnl_websiteTravelCardContainerLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnl_websiteTravelCardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_websiteTravelCardContainerLayout.createSequentialGroup()
                                .addComponent(lbl_websiteTCBalance)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_websiteTCBalanceInput))
                            .addGroup(pnl_websiteTravelCardContainerLayout.createSequentialGroup()
                                .addComponent(lbl_websiteTCStartDate)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_websiteTCStartDateInput)
                                .addGap(118, 118, 118)
                                .addComponent(lbl_websiteTCExpiryDate)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_websiteTCExpiryDateInput))
                            .addGroup(pnl_websiteTravelCardContainerLayout.createSequentialGroup()
                                .addComponent(lbl_websiteTCDiscount)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_websiteTCDiscountInput))
                            .addGroup(pnl_websiteTravelCardContainerLayout.createSequentialGroup()
                                .addComponent(lbl_websiteTCDailyCap)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_websiteTCDailyCapInput)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_websiteTravelCardContainerLayout.setVerticalGroup(
            pnl_websiteTravelCardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_websiteTravelCardContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(pnl_websiteTravelCardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_websiteTCBalance)
                    .addComponent(lbl_websiteTCBalanceInput))
                .addGap(18, 18, 18)
                .addGroup(pnl_websiteTravelCardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_websiteTCStartDate)
                    .addComponent(lbl_websiteTCExpiryDate)
                    .addComponent(lbl_websiteTCStartDateInput)
                    .addComponent(lbl_websiteTCExpiryDateInput))
                .addGap(18, 18, 18)
                .addGroup(pnl_websiteTravelCardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_websiteTCDiscount)
                    .addComponent(lbl_websiteTCDiscountInput))
                .addGap(18, 18, 18)
                .addGroup(pnl_websiteTravelCardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_websiteTCDailyCap)
                    .addComponent(lbl_websiteTCDailyCapInput))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_websiteMainContainerLayout = new javax.swing.GroupLayout(pnl_websiteMainContainer);
        pnl_websiteMainContainer.setLayout(pnl_websiteMainContainerLayout);
        pnl_websiteMainContainerLayout.setHorizontalGroup(
            pnl_websiteMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_websiteMainContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_websiteMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_websiteMainContainerLayout.createSequentialGroup()
                        .addComponent(btn_websiteMainLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_websiteMainAccount)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_websiteMainTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_websiteMainContainerLayout.createSequentialGroup()
                        .addGroup(pnl_websiteMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_websiteTicketsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_websiteTravelCardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(pnl_websiteHistoryContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_websiteMainContainerLayout.setVerticalGroup(
            pnl_websiteMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_websiteMainContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_websiteMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_websiteMainLogout)
                    .addComponent(btn_websiteMainAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_websiteMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_websiteMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_websiteHistoryContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_websiteMainContainerLayout.createSequentialGroup()
                        .addComponent(pnl_websiteTicketsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_websiteTravelCardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.setEnabled(false);

        javax.swing.GroupLayout pnl_websiteContainerLayout = new javax.swing.GroupLayout(pnl_websiteContainer);
        pnl_websiteContainer.setLayout(pnl_websiteContainerLayout);
        pnl_websiteContainerLayout.setHorizontalGroup(
            pnl_websiteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_websiteContainerLayout.createSequentialGroup()
                .addGroup(pnl_websiteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_websiteContainerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_websiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_websiteURLGo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_websiteMainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_websiteContainerLayout.setVerticalGroup(
            pnl_websiteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_websiteContainerLayout.createSequentialGroup()
                .addGroup(pnl_websiteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_websiteURL, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_websiteURLGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_websiteMainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_websiteContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_websiteContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        mainUI.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loginPopup.pack();
        loginPopup.setLocationRelativeTo(null);
        lbl_loginErrorMsg.setVisible(false);
        loginPopup.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void txt_registerFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registerFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_registerFirstNameActionPerformed

    // sets error states inside register form if there is any issues
    private boolean checkUsersRegistrationInput(String firstName, String surname,
            String username, String email, String password, SystemRole newSysRole, String dob) {

        boolean isValid = true;

        if (firstName.isEmpty()) {
            lbl_registerFirstNameError.setVisible(true);
            isValid = false;
        } else {
            lbl_registerFirstNameError.setVisible(false);
        }

        if (surname.isEmpty()) {
            lbl_registerLastNameError.setVisible(true);
            isValid = false;
        } else {
            lbl_registerLastNameError.setVisible(false);
        }

        if (username.isEmpty()) {
            lbl_registerUsernameError.setText("Required");
            lbl_registerUsernameError.setVisible(true);
            isValid = false;
        } else {
            try {
                // if username is already taken
                if (TravelSystem.getInstance().getUsers().getUserByUsername(username) != null) {
                    lbl_registerUsernameError.setText("Username already exists!");
                    lbl_registerUsernameError.setVisible(true);
                    isValid = false;
                } else {
                    lbl_registerUsernameError.setVisible(false);
                }
            } catch (Throwable ex) {
                Logger.getLogger(WebsiteUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (email.isEmpty()) {
            lbl_registerEmailError.setText("Required");
            lbl_registerEmailError.setVisible(true);
            isValid = false;
        } else {
            try {
                // if email is already taken
                if (TravelSystem.getInstance().getUsers().getUserByEmail(email) != null) {
                    lbl_registerEmailError.setText("Email already exists!");
                    lbl_registerEmailError.setVisible(true);
                    isValid = false;
                } else {
                    lbl_registerEmailError.setVisible(false);
                }
            } catch (Throwable ex) {
                Logger.getLogger(WebsiteUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (password.isEmpty()) {
            lbl_registerPasswordError.setVisible(true);
            isValid = false;
        } else {
            lbl_registerPasswordError.setVisible(false);
        }

        if (dob.isEmpty()) {
            lbl_registerDobError.setVisible(true);
            isValid = false;
        } else {
            lbl_registerDobError.setVisible(false);
        }

        // returns true allowing user to register if everything checks out
        if (isValid) {
            return true;
        }
        return false;

    }

    private void btn_RegisterSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterSubmitActionPerformed
        String firstName = txt_registerFirstName.getText();
        String surname = txt_registerLastName.getText();
        String username = txt_registerUsername.getText();
        String email = txt_registerEmail.getText();
        String password = new String(pass_registerPassword.getPassword());
        String dob = txt_registerDob.getText().replace("/", "-");
        SystemRole newSysRole = new SystemRole(TypeEnums.UserType.USER);

        boolean isValid = checkUsersRegistrationInput(firstName, surname,
                username, email, password, newSysRole, dob);

        if (isValid) {
            try {
                TravelSystem.getInstance()
                        .registerUser(null, firstName, surname, username, email, null, password, newSysRole, dob);
                TravelSystem.getInstance().serializeUsers(); // save users with new user
            } catch (Throwable ex) {
                Logger.getLogger(WebsiteUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                this.user = TravelSystem.getInstance().getUsers().getUserByUsername(username);
            } catch (Throwable ex) {
                Logger.getLogger(WebsiteUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            openWebsiteUI();
        }
    }//GEN-LAST:event_btn_RegisterSubmitActionPerformed

    private void registerPopupWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_registerPopupWindowClosing
//        loginPopup.setEnabled(true);
    }//GEN-LAST:event_registerPopupWindowClosing

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        loginPopup.dispose();
        this.dispose();
        mainUI.setEnabled(true);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        //Reset register inputs
        txt_registerFirstName.setText("");
        txt_registerLastName.setText("");
        txt_registerUsername.setText("");
        txt_registerEmail.setText("");
        pass_registerPassword.setText("");
        txt_registerDob.setText("");

        // re-hide register error messages
        lbl_registerFirstNameError.setVisible(false);
        lbl_registerLastNameError.setVisible(false);
        lbl_registerPasswordError.setVisible(false);
        lbl_registerUsernameError.setVisible(false);
        lbl_registerEmailError.setVisible(false);
        lbl_registerDobError.setVisible(false);

        registerPopup.pack();
        registerPopup.setLocationRelativeTo(null);
        registerPopup.setVisible(true);
    }//GEN-LAST:event_btn_registerActionPerformed

    private void throwLoginError(String error) {
        lbl_loginErrorMsg.setText(error);
        lbl_loginErrorMsg.setVisible(true);
    }

    private void login() {
        String username = txt_username.getText();
        String password = new String(pass_password.getPassword());

        try {
            user = TravelSystem.getInstance().getUsers().getUserByUsername(username);
            if (user != null) {
                if (user.authenticateUser(password)) {
                    if (user.getSystemRole().isAdmin()) {
                        lbl_loginErrorMsg.setVisible(false);
                        openAdminUI(username);
                    } else {
                        lbl_loginErrorMsg.setVisible(false);
                        openWebsiteUI();
                    }
                } else {
                    /* don't want anymore information
                     * telling the user that a user exists with this information
                     * would potentially enable security flaws
                     */
                    throwLoginError("Credentials Invalid");
                }
            } else {
                throwLoginError("Credentials Invalid");
            }
        } catch (Throwable ex) {
            System.out.println(ex);
            throwLoginError("Something went wrong");

        }
    }

    private void btn_loginPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginPopupActionPerformed
        // seperated from keypress so it can be used on input key listeners for
        // enter key click
        login();
    }//GEN-LAST:event_btn_loginPopupActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void loginPopupWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loginPopupWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_loginPopupWindowClosing

    private void txt_websiteURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_websiteURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_websiteURLActionPerformed

    private void btn_websiteMainLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_websiteMainLogoutActionPerformed
        this.dispose();
        mainUI.setEnabled(true);
    }//GEN-LAST:event_btn_websiteMainLogoutActionPerformed

    private void txt_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyReleased
        // attach keyListener, listening for 'enter' key presses to fire login
        if (evt.getKeyCode() == 10) {
            login();
        }
    }//GEN-LAST:event_txt_usernameKeyReleased

    private void pass_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_passwordKeyReleased
        // attach keyListener, listening for 'enter' key presses to fire login
        if (evt.getKeyCode() == 10) {
            login();
        }
    }//GEN-LAST:event_pass_passwordKeyReleased

    private void btn_RegisterCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterCancelActionPerformed
        // TODO add your handling code here:
        registerPopup.setVisible(false);
    }//GEN-LAST:event_btn_RegisterCancelActionPerformed

    private void cmb_websiteToZoneListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_websiteToZoneListActionPerformed

    }//GEN-LAST:event_cmb_websiteToZoneListActionPerformed

    private void cmb_websiteFromZoneListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_websiteFromZoneListActionPerformed
        // When the index of the from zone list is changed, update the 'to zone'
        // list
        setUpToJourneyList();
    }//GEN-LAST:event_cmb_websiteFromZoneListActionPerformed

    private void btn_websitePurchaseTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_websitePurchaseTicketActionPerformed
        if (handleTransaction()) {
            this.lbl_websitePurchaseMessage.setText("Purchase Successful");
            this.lbl_websitePurchaseMessage.setForeground(Color.GREEN);
        } else {
            this.lbl_websitePurchaseMessage.setText("Purchase Unsuccessful");
            this.lbl_websitePurchaseMessage.setForeground(Color.RED);
        }

        setUpTravelCardDetails();
    }//GEN-LAST:event_btn_websitePurchaseTicketActionPerformed

    private void openAdminUI(String username) {
        loginPopup.dispose();
        this.setEnabled(false);
        this.setVisible(false);

        JFrame adminUI = new AdminUI(username);
        adminUI.setLocationRelativeTo(null);
        adminUI.setVisible(true);
        adminUI.setResizable(false);
    }

    private void openWebsiteUI() {
        registerPopup.dispose();
        loginPopup.dispose();
        this.setLocationRelativeTo(null);
        this.setEnabled(true);
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUpTravelCardDetails();
    }

    private void setUpTravelCardDetails() {
        TravelCard currentTravelCard = null;

        // Get the travel card corresponding to the current user
        try {
            currentTravelCard = TravelSystem.getInstance().getTravelCards().getTravelCardById(this.user.getTravelCardId());
        } catch (Throwable ex) {
            Logger.getLogger(WebsiteUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Read the data from a travel card and display it on the UI
        this.lbl_websiteTCBalanceInput.setText(String.format("%.2f", currentTravelCard.getBalance()));
        this.lbl_websiteTCDailyCapInput.setText(Float.toString(currentTravelCard.getDailyCap()));
        this.lbl_websiteTCDiscountInput.setText(Float.toString(currentTravelCard.getDiscount()));
        this.lbl_websiteTCExpiryDateInput.setText(currentTravelCard.getExpiryDate().toString());
        this.lbl_websiteTCStartDateInput.setText(currentTravelCard.getCreationDate().toString());

        // Populate the user journey table
        setUpUserJourneyTable();
        // Set up the zone combo boxes
        setUpZoneLists();
        // Set up ticket type list
        setUpTicketTypes();
    }

    private void setUpTicketTypes() {
        // Clear the list first
        this.cmb_websiteTicketType.removeAllItems();

        // Then add the potential ticket types to the list
        for (TypeEnums.TicketType ticketType : TypeEnums.TicketType.values()) {
            this.cmb_websiteTicketType.addItem(ticketType.toString());
        }
    }

    private void setUpZoneLists() {
        TravelSystem system = null;
        try {
            system = TravelSystem.getInstance();
        } catch (Throwable ex) {
            Logger.getLogger(WebsiteUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Display all of the potential departure zones
        this.cmb_websiteFromZoneList.removeAllItems();
        SetOfZones zoneList = system.getZones();
        for (Zone zone : zoneList) {
            if (!system.getJourneys().getAllZonesDepartingFromStartZone(zone).isEmpty()) {
                this.cmb_websiteFromZoneList.addItem(zone);
            }
        }

        setUpToJourneyList();
    }

    private void setUpToJourneyList() {
        TravelSystem system = null;
        try {
            system = TravelSystem.getInstance();
        } catch (Throwable ex) {
            Logger.getLogger(WebsiteUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Make sure the combo box is clear before re-populating
        this.cmb_websiteToZoneList.removeAllItems();

        // If the selected from zone is not null
        if (this.cmb_websiteFromZoneList.getItemAt(0) != null) {
            // Get all of the zones that the user can travel to from the selected
            // zone
            SetOfZones toZones = system.getJourneys()
                    .getAllZonesDepartingFromStartZone((Zone) this.cmb_websiteFromZoneList.getSelectedItem());

            // Add the potential destination zones to the list
            toZones.stream().forEach((zone) -> {
                this.cmb_websiteToZoneList.addItem(zone);
            });
        }
    }

    private boolean handleTransaction() {
        TravelSystem system = null;
        try {
            system = TravelSystem.getInstance();
        } catch (Throwable ex) {
            Logger.getLogger(WebsiteUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Create a new Transaction so that we can handle ticket payment
        Transaction transaction = new Transaction();
        // The users pass does not cover their desired journey,
        // so create a ticket
        Journey journey = system.getJourneys().getJourney(
                (Zone) this.cmb_websiteFromZoneList.getSelectedItem(),
                (Zone) this.cmb_websiteToZoneList.getSelectedItem());

        TypeEnums.TicketType ticketType = null;
        // Discern whether the user wants a bus or train ticket
        if ("TRAIN".equals(this.cmb_websiteTicketType.getSelectedItem())) {
            ticketType = TypeEnums.TicketType.TRAIN;
        } else if ("BUS".equals(this.cmb_websiteTicketType.getSelectedItem())) {
            ticketType = TypeEnums.TicketType.BUS;
        }

        // Create a new 'ticket' for this journey
        Ticket newTicket = null;
        try {
            // Create a new ticket, set it as not used
            newTicket = new Ticket(TravelSystem.getInstance().getTickets()
                    .getNextId(), ticketType, journey, journey.getStartZone().isPeak(), user.getId(), false);
        } catch (Throwable ex) {
            Logger.getLogger(PortableReaderUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Pay for the ticket, returns true if the payment was successful
        return transaction.payForTicket(newTicket, system.getTravelCards().getTravelCardById(user.getTravelCardId()));
    }

    private void setUpUserJourneyTable() {
        DefaultTableModel model = (DefaultTableModel) this.tbl_websiteUserJourneysTaken.getModel();
        // Reset table before setting it up
        model.setRowCount(0);

        tbl_websiteUserJourneysTaken.setCellSelectionEnabled(false);
        tbl_websiteUserJourneysTaken.setRowSelectionAllowed(true);

        TravelSystem system = null;

        // Get the travel card corresponding to the current user
        try {
            system = TravelSystem.getInstance();
        } catch (Throwable ex) {
            Logger.getLogger(WebsiteUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Get the users tickets
        SetOfTickets userTickets = system.getTickets().getTicketsForUser(this.user.getId());
        // Extract useful information and add it to the table
        userTickets.stream().forEach((ticket) -> {
            model.addRow(new Object[]{
                ticket.getJourney().getStartZone(),
                ticket.getJourney().getEndZone(),
                String.format("%.2f", ticket.getJourney().getPriceBasedOnPeak(ticket.isPeakTicket())),
                ticket.getTicketType(),
                ticket.getIsUsed()
            });
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WebsiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WebsiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WebsiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WebsiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_RegisterCancel;
    private javax.swing.JButton btn_RegisterSubmit;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_loginPopup;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btn_websiteMainAccount;
    private javax.swing.JButton btn_websiteMainLogout;
    private javax.swing.JButton btn_websitePurchaseTicket;
    private javax.swing.JButton btn_websiteURLGo;
    private javax.swing.JComboBox cmb_websiteFromZoneList;
    private javax.swing.JComboBox cmb_websiteTicketType;
    private javax.swing.JComboBox cmb_websiteToZoneList;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_loginErrorMsg;
    private javax.swing.JLabel lbl_loginTitle;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_registerDob;
    private javax.swing.JLabel lbl_registerDobError;
    private javax.swing.JLabel lbl_registerEmail;
    private javax.swing.JLabel lbl_registerEmailError;
    private javax.swing.JLabel lbl_registerFirstName;
    private javax.swing.JLabel lbl_registerFirstNameError;
    private javax.swing.JLabel lbl_registerLastName;
    private javax.swing.JLabel lbl_registerLastNameError;
    private javax.swing.JLabel lbl_registerPassword;
    private javax.swing.JLabel lbl_registerPasswordError;
    private javax.swing.JLabel lbl_registerTitle;
    private javax.swing.JLabel lbl_registerUsername;
    private javax.swing.JLabel lbl_registerUsernameError;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_websiteFromTag;
    private javax.swing.JLabel lbl_websitePurchaseMessage;
    private javax.swing.JLabel lbl_websiteTCBalance;
    private javax.swing.JLabel lbl_websiteTCBalanceInput;
    private javax.swing.JLabel lbl_websiteTCDailyCap;
    private javax.swing.JLabel lbl_websiteTCDailyCapInput;
    private javax.swing.JLabel lbl_websiteTCDiscount;
    private javax.swing.JLabel lbl_websiteTCDiscountInput;
    private javax.swing.JLabel lbl_websiteTCExpiryDate;
    private javax.swing.JLabel lbl_websiteTCExpiryDateInput;
    private javax.swing.JLabel lbl_websiteTCStartDate;
    private javax.swing.JLabel lbl_websiteTCStartDateInput;
    private javax.swing.JLabel lbl_websiteToTag;
    private javax.swing.JLabel lbl_websiteToTag1;
    private javax.swing.JDialog loginPopup;
    private javax.swing.JPasswordField pass_password;
    private javax.swing.JPasswordField pass_registerPassword;
    private javax.swing.JPanel pnl_registerContainer;
    private javax.swing.JPanel pnl_websiteContainer;
    private javax.swing.JPanel pnl_websiteHistoryContainer;
    private javax.swing.JPanel pnl_websiteMainContainer;
    private javax.swing.JPanel pnl_websiteTicketsContainer;
    private javax.swing.JPanel pnl_websiteTravelCardContainer;
    private javax.swing.JDialog registerPopup;
    private javax.swing.JTable tbl_websiteUserJourneysTaken;
    private javax.swing.JTextField txt_registerDob;
    private javax.swing.JTextField txt_registerEmail;
    private javax.swing.JTextField txt_registerFirstName;
    private javax.swing.JTextField txt_registerLastName;
    private javax.swing.JTextField txt_registerUsername;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel txt_websiteMainTitle;
    private javax.swing.JTextField txt_websiteURL;
    // End of variables declaration//GEN-END:variables

}
